### PR TITLE
fix: correct link paths in docs

### PR DESCRIPTION
**Pull request by bhajneet**
### Summary of PR
brief_summary_plz

### Tests for unexpected behavior
- none_whatsoever

### Time spent on PR
nine_thousand_years

### Linked issues
Fix #

### CODE REVIEW

**Comment by bhajneet** [comment]
@Harjot1Singh please see second commit.

**Comment by Harjot1Singh** [comment]
@bhajneet don't need second commit - the next PR coming already has a `config/README.md`

**Comment by bhajneet** [comment]
May I recommend you add that line to the next PR?

**Comment by bhajneet** [comment]
Else, close this PR and add first commit to your next PR

**Review by Harjot1Singh — APPROVED** [review]

**Pull request merged**
